# Generated by Django 2.1.4 on 2018-12-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181230_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
