# Generated by Django 2.1.4 on 2018-12-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.OneToOneField(default=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department'),
        ),
    ]
