# Generated by Django 2.1.4 on 2018-12-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20181230_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.OneToOneField(default=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.School'),
        ),
    ]
