# Generated by Django 2.1.4 on 2019-01-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190114_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.OneToOneField(default=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.OneToOneField(default=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.School'),
        ),
    ]
