# Generated by Django 2.1.4 on 2019-01-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190114_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
