# Generated by Django 2.1.4 on 2019-01-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0015_auto_20190114_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sex', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=True)),
                ('section', models.PositiveIntegerField(default=True, null=True)),
                ('department', models.OneToOneField(default=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('school', models.OneToOneField(default=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
