# Generated by Django 2.1.4 on 2019-01-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
