# Generated by Django 2.1.4 on 2019-03-03 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0005_topic_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendix',
            name='content_raw',
            field=models.TextField(verbose_name='raw content'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='content_rendered',
            field=models.TextField(blank=True, default='', verbose_name='rendered content'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published time'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niji.Topic', verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niji.Post', verbose_name='reply'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niji.Topic', verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_raw',
            field=models.TextField(verbose_name='raw content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_rendered',
            field=models.TextField(default='', verbose_name='rendered content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='niji.Topic', verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_raw',
            field=models.TextField(verbose_name='raw content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_rendered',
            field=models.TextField(blank=True, default='', verbose_name='rendered content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_replied',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='last replied time'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='niji.Node', verbose_name='node'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=10, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='published time'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='reply count'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='view count'),
        ),
    ]
