# Generated by Django 2.1.4 on 2018-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20181224_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'MC'), ('Short Answer', 'SA'), ('True or False', 'TF'), ('Fill in the blanks', 'FITB'), ('Flash Card', 'FC')], max_length=50),
        ),
    ]
