# Generated by Django 2.1.4 on 2018-12-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20181229_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
