# Generated by Django 2.1.4 on 2018-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20181229_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='file',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='slide',
            name='file',
            field=models.CharField(max_length=256),
        ),
    ]
