# Generated by Django 2.1.4 on 2018-12-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20181229_2029'),
        ('resources', '0007_question_chapter'),
    ]

    operations = [
    ]
