# Generated by Django 2.1.4 on 2018-12-30 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_merge_20181229_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
