# Generated by Django 2.1.4 on 2018-12-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_merge_20181229_2336'),
        ('resources', '0012_auto_20181230_0555'),
    ]

    operations = [
    ]
