# Generated by Django 2.1.4 on 2019-01-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20181230_1514'),
        ('resources', '0014_auto_20181230_1201'),
    ]

    operations = [
    ]
